import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);globalThis.Sand=require('./sand.js');globalThis.SandBoard=require('./board.js');
const Game=await import('./gamelogic.js'),{EditorStore}=await import('./static/js/editor-store.js'),{LocalFiles}=await import('./static/js/local-files.js');
const config=JSON.parse(fs.readFileSync('config.json')),assets=JSON.parse(fs.readFileSync('asset.json'));const names=fs.readdirSync('level').filter(n=>/^level-\d+\.json$/.test(n));
const records=names.map(name=>({path:'level/'+name,name,data:JSON.parse(fs.readFileSync('level/'+name))}));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');let bad=[],drawCalls=0;
for(const r of records){assert.equal(hash(fs.readFileSync(r.path)),hash(fs.readFileSync('levels/level_'+r.data.id+'.json')),'working copy modified '+r.data.id);const e=Game.validateLevel(r.data,assets);if(e.length)bad.push({id:r.data.id,errors:e});
  const canvas={width:config.thumbnail.width,height:config.thumbnail.height};const ctx=new Proxy({canvas},{get:(o,k)=>k in o?o[k]:(...args)=>{if(['fillRect','strokeRect','moveTo','lineTo','clearRect'].includes(k)){assert.ok(args.every(Number.isFinite));drawCalls++;}}});Game.drawLevel(ctx,r.data,{assets});
}
assert.deepEqual(bad.map(r=>r.id).sort((a,b)=>a-b),[8,257]);
assert.ok(Game.levelWarnings(records.find(r=>r.data.id===568).data).some(s=>s.includes('沙量')));
const sample=Game.createEmptyLevel({id:578,config,assets});assert.deepEqual(Game.validateLevel(sample,assets),[]);const session=Game.createSession(sample,config);session.move(session.pits[0],1,2);for(let i=0;i<100&&!session.won;i++)session.advance(.02);assert.ok(session.won);assert.equal(sample.m_creationData.pits[0].StartPosition.y,1);
const readonly=new EditorStore({config,assets,levels:records});assert.throws(()=>readonly.addLevel(),/只读/);await assert.rejects(()=>readonly.save(),/只读/);
let calls=[],disk=new Map(records.map(r=>[r.path,JSON.stringify(r.data)])),failOn=null;
const api={write_text:async(path,value,overwrite)=>{calls.push(['write',path,overwrite]);if(path===failOn)return {ok:false,error:{code:'TEST_IO',message:'test write failure'}};if(!overwrite&&disk.has(path))return {ok:false,error:{code:'EXISTS',message:'exists'}};disk.set(path,value);return {ok:true,data:{}};},write_base64:async(path,value,overwrite)=>{calls.push(['image',path,overwrite]);disk.set(path,value);return {ok:true,data:{}};},mkdir:async()=>({ok:true,data:{}}),delete:async path=>{calls.push(['delete',path]);disk.delete(path);return {ok:true,data:{}};}};
const store=new EditorStore({config,assets,levels:records,files:new LocalFiles(api)});store.select(58);await store.save();assert.equal(calls.length,0,'clean save must not rewrite originals');
store.updateLevel(l=>l.m_Name='测试名称');assert.equal(calls.length,0);store.undo();assert.equal(store.dirty,false);store.redo();await store.save();assert.deepEqual(calls.map(c=>c[1]),['level/level-58.json']);assert.equal(store.dirty,false);
assert.throws(()=>store.deleteAsset('color-0'),/引用/);assert.throws(()=>store.updateAsset('color-0',{...Game.allAssets(assets).find(a=>a.id==='color-0'),colorIndex:15}),/引用/);
store.addLevel();const first=store.current;store.addLevel();const second=store.current;failOn=second.path;await assert.rejects(()=>store.save(),/test write failure/);assert.ok(store.dirty);assert.ok(disk.has(first.path));failOn=null;calls=[];await store.save();assert.deepEqual(calls,[['write',second.path,false]]);assert.equal(store.dirty,false);
const img='level/asset/test-image.png';store.updateAsset(null,{id:'new-swatch',name:'新颜色',type:'color',colorIndex:15,color:'#ffffff',image:img},'YWJj');assert.ok(store.images.size);store.undo();assert.equal(store.images.size,0);store.redo();calls=[];await store.save();assert.equal(calls[0][0],'image');assert.ok(calls.some(c=>c[1]==='asset.json'));
store.deleteLevel();calls=[];assert.equal(disk.has(second.path),true);await store.save();assert.ok(calls.some(c=>c[0]==='delete'&&c[1]===second.path));
// JSON preserves arbitrary unknown fields across edits and saves.
store.select(58);store.updateLevel(l=>l.unknown_future_field={opaque:[1,'a']});await store.save();assert.deepEqual(JSON.parse(disk.get('level/level-58.json')).unknown_future_field,{opaque:[1,'a']});
const difficulty=JSON.parse(fs.readFileSync('difficulty-results.json'));for(const id of [58,13,163,400]){const expected=difficulty.levels.find(r=>r.id===id);assert.equal(Game.calculateDifficulty(records.find(r=>r.data.id===id).data,assets,config).score,expected.coefficient);}
console.log('PASS: 577 byte-identical working copies and Canvas thumbnails; 2 structural errors preserved; minimal level wins; read-only enforcement; touched-only save; undo/redo; asset references; image staging; partial-save retry; new-file overwrite=false; staged deletion; unknown fields; difficulty parity. Draw calls: '+drawCalls);
fs.writeFileSync('editor-verification.json',JSON.stringify({levelCount:records.length,structuralErrors:bad,drawCalls,scope:'Node contract tests; real WebView file API not exercised',passed:true},null,2));
